//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mvc_Jashim.Models
{
    using System;
    using System.Collections.Generic;

    using System.Web;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using Library_Mvc_Jashim.Custom_Validation;

    public partial class Book
    {
        [Required(ErrorMessage = "BookID is Required.")]
        public int BookID { get; set; }

        [Required(ErrorMessage = "Book Name must be supplied.")]

        public string Title { get; set; }

        [Required(ErrorMessage = "Author Name is Necessary.")]
        public string Author { get; set; }


        [Required(ErrorMessage = "Short Description is necessary.")]
        [StringLength(15, MinimumLength = 4, ErrorMessage = "Description must be in between 4 to 15 charecters.")]
        public string Description { get; set; }
        public int CategoryID { get; set; }

        [Required]
        //[DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [CustomAddedDate(ErrorMessage = "Book Addition Date must be less than or equal to Today's Date")]
        [Display(Name = "Added Time ")]
        public DateTime AddedTime { get; set; }

        [DisplayName("Image")]
        public string ImagePath { get; set; }
    
        public virtual BookCategory BookCategory { get; set; }


        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }


        public Book()
        {
            ImagePath = "~/Images/default.png";
        }

    }

}
